### ISSUE TITLE
services: Unify error handling

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/storage#118]
Proposal: https://github.com/Xuanwo/storage/blob/master/docs/design/11-error-handling.md
Spec: https://github.com/Xuanwo/storage/blob/master/docs/spec/1-error-handling.md

- [x] azblob
- [x] cos
- [x] dropbox
- [x] fs
- [x] gcs
- [x] kodo
- [x] oss
- [x] qingstor
- [x] s3
- [x] uss

**Comment by Prnyself** [comment]
qingstor error handle not work as intended:

- Qingstor sdk returns error as the pointer of QingStorError

**Comment by Xuanwo** [comment]
https://github.com/Xuanwo/storage/pull/141 will fix `fs` support

**Comment by Xuanwo** [comment]
#143 fix `azblob` support

**Comment by Xuanwo** [comment]
#146 fix `dropbox` support
#148 fix `gcs` support

**Comment by Xuanwo** [comment]
#149 fix `kodo` support

**Comment by Xuanwo** [comment]
#150 fix `oss` support

**Comment by Xuanwo** [comment]
#152 fix `s3` support

**Comment by Xuanwo** [comment]
#153 fix `uss` support
