### ISSUE TITLE
GCS如何配置config string?

### ISSUE THREAD

**Issue by lonely2099** [Xuanwo/storage#214]
懵逼中，尝试了很多次都失败，貌似是仓库地址和 x-goog-project-id 的问题，能否帮我看下，我该怎么配置连接字符串,  例如:

access_key:  abc   
secret_key:   qwe
project-id:    123456
url:   https://console.cloud.google.com/storage/browser/bucket123
怎么配是对的？
gcs://static:abc:qwe@https:console.cloud.google.com:443/bucket123
gcs://static:abc:qwe@https:console.cloud.google.com:443/bucket123/?x-goog-project-id=123456

都是错的，我该怎么配置？谢谢！

**Comment by lonely2099** [comment]
s3的折腾也没成功，有点崩溃怀疑人生了。。

**Comment by Xuanwo** [comment]
在 proposal [13-remove-config-string](https://storage.xuanwo.io/design/13-remove-config-string) 里面已经去掉 config string 的概念了，因为 config string 不太好用。你可以升级到 v0.8.0 并这样使用：

```go
_, store, err := Open(gcs.Type,
	pairs.WithCredential(credential.MustNewAPIKey("api_key_here")),
	pairs.WithProject("project_id_here"),
	pairs.WithName("bucket_name_here"),
)
if err != nil {
	log.Fatalf("service init failed: %v", err)
}
```

**Comment by lonely2099** [comment]
确定不需要secret_access_key吗？  google 的HMAC，需要 访问密钥，密钥，以及project_id
access_key: abc
secret_key: qwe
project-id: 123456
url: https://console.cloud.google.com/storage/browser/bucket123

这样使用吗？
_, store, err := coreutils.Open(gcs.Type,
	pairs.WithCredential(credential.MustNewAPIKey("abc")),
	pairs.WithProject("123456"),
	pairs.WithName("bucket123"),
)
if err != nil {
	log.Fatalf("service init failed: %v", err)
}

**Comment by Xuanwo** [comment]
gcs 目前只支持通过 api key 的方式访问，hmac 的支持可以提一个 issue，在 0.9 发布之后会考虑支持

**Comment by lonely2099** [comment]
好吧，非常感谢热心回复，建议移除掉旧的文档吧，毕竟项目开始没有很久，不太完善，容易掉坑里！

**Comment by Xuanwo** [comment]
嗯，现在还在做很多大规模的改动，预计到 0.9 之后会逐步稳定，之后会一起更新

**Comment by lonely2099** [comment]
那我现在可以使用它，来应用在正式项目吗？

**Comment by Xuanwo** [comment]
建议等到 1.0 发布之后再使用，否则需要跟随版本发布持续修改 API 变更的地方
