### ISSUE TITLE
Read failed with error 'use of closed network connection'

### ISSUE THREAD

**Issue by Prnyself** [Xuanwo/storage#302]
When copy files from local `fs` to `qingstor`, it will failed with error `write tcp {ip1}->{ip2}: use of closed network connection` if some files were not small and cost a few seconds.

**Comment by Xuanwo** [comment]
Related to https://github.com/golang/go/issues/11745

**Comment by Prnyself** [comment]
[here](https://gist.github.com/Prnyself/fd653694d9d064f3276d48eb4fbc86c7) is the code.

**Comment by Xuanwo** [comment]
httpclient used to set read/write deadline separately which lead to connetion closed while writing (no read occur).
